"""Reusable helpers for the Module 8 Grad Cafe cleaning / EDA notebook.

The notebook (``module_8.ipynb``) keeps all of the Pandas/NumPy/SciPy *analysis*
visible inline so the work is easy to follow. This module holds only the
mechanical, repetitive pieces that would otherwise clutter the notebook:

* ``render_table_png`` -- save any DataFrame/Series as a PNG "screenshot" so the
  required image deliverables are generated by code and are reproducible.
* the six Matplotlib figures (each saved as its own labelled PNG), and
* ``build_analytics_pdf`` -- render the written analytical summary to a PDF.

Keeping these here avoids copy-pasted plotting boilerplate (assignment: "avoid
repetitive code by writing helper functions where appropriate") while leaving the
substantive data work in the notebook.
"""

import textwrap

import matplotlib
matplotlib.use("Agg")  # headless-safe on SageMaker
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.backends.backend_pdf import PdfPages


# --------------------------------------------------------------------------- #
# Rendering DataFrames / Series to PNG (the "screenshot" deliverables)
# --------------------------------------------------------------------------- #
def _truncate(value, width=22):
    """Shorten a cell value so wide tables stay legible in a PNG."""
    text = "" if value is None else str(value)
    return text if len(text) <= width else text[: width - 1] + "…"


def render_table_png(frame, path, title=None, max_rows=5, index=True):
    """Save ``frame`` (DataFrame or Series) as a table image at ``path``.

    Only the first ``max_rows`` rows are drawn. This is the code-generated
    stand-in for a manual screenshot, so the image deliverables are reproducible.
    """
    if isinstance(frame, pd.Series):
        frame = frame.to_frame()
    view = frame.head(max_rows).copy()

    col_labels = [str(c) for c in view.columns]
    cell_text = [[_truncate(v) for v in row] for row in view.itertuples(index=False)]
    if index:
        col_labels = [""] + col_labels
        cell_text = [[_truncate(idx)] + row for idx, row in zip(view.index, cell_text)]

    n_cols = max(len(col_labels), 1)
    fig_w = min(2 + 1.5 * n_cols, 26)
    fig_h = 1.2 + 0.45 * (len(cell_text) + 1)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.axis("off")
    if title:
        ax.set_title(title, fontweight="bold", pad=12)

    table = ax.table(cellText=cell_text or [[""]], colLabels=col_labels,
                     cellLoc="left", loc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.4)
    for (r, _c), cell in table.get_celld().items():
        if r == 0:
            cell.set_text_props(fontweight="bold", color="white")
            cell.set_facecolor("#40466e")
    fig.tight_layout()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


# --------------------------------------------------------------------------- #
# Visualizations (assignment section 7)
# --------------------------------------------------------------------------- #
def _bestfit(x, y):
    """Return (xs, ys, label) for a degree-1 NumPy least-squares fit."""
    coeffs = np.polyfit(x, y, 1)
    xs = np.linspace(np.min(x), np.max(x), 100)
    ys = np.polyval(coeffs, xs)
    label = f"best-fit: y = {coeffs[0]:.2f}x + {coeffs[1]:.2f}"
    return xs, ys, label


def scatter_gre_vs_grev(df, path):
    """Scatter of non-zero GRE vs GRE V with a NumPy best-fit line."""
    sub = df[(df["GRE"] > 0) & (df["GRE V"] > 0)][["GRE", "GRE V"]].dropna()
    x, y = sub["GRE"].to_numpy(), sub["GRE V"].to_numpy()
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.scatter(x, y, s=14, alpha=0.5, color="#2b6cb0", label="applicants")
    if len(sub) >= 2:
        xs, ys, lbl = _bestfit(x, y)
        ax.plot(xs, ys, color="#c53030", lw=2, label=lbl)
    ax.set_title("GRE (Quant) vs GRE Verbal")
    ax.set_xlabel("GRE Quantitative (130-170 scale)")
    ax.set_ylabel("GRE Verbal (130-170 scale)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def scatter_gpa_vs_gre(df, path):
    """Scatter of valid GPA (0-4) vs non-zero GRE with a NumPy best-fit line."""
    sub = df[(df["GPA"].between(0, 4.0)) & (df["GRE"] > 0)][["GPA", "GRE"]].dropna()
    x, y = sub["GPA"].to_numpy(), sub["GRE"].to_numpy()
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.scatter(x, y, s=14, alpha=0.5, color="#2f855a", label="applicants")
    if len(sub) >= 2:
        xs, ys, lbl = _bestfit(x, y)
        ax.plot(xs, ys, color="#c53030", lw=2, label=lbl)
    ax.set_title("GPA vs GRE (Quant)")
    ax.set_xlabel("GPA (4.0 scale)")
    ax.set_ylabel("GRE Quantitative (130-170 scale)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def bar_degree_by_international(df, path):
    """Grouped bar chart: Degree counts broken down by US/International."""
    ct = pd.crosstab(df["Degree"], df["US/International"])
    fig, ax = plt.subplots(figsize=(8, 6))
    ct.plot(kind="bar", ax=ax)
    ax.set_title("Applicants by Degree, split by US/International")
    ax.set_xlabel("Degree")
    ax.set_ylabel("Number of applicants (count)")
    ax.tick_params(axis="x", rotation=0)
    ax.legend(title="US/International")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def hist_acceptances_over_time(df, path):
    """Histogram of Accepted applicants by decision_date in 3-day bins."""
    dates = df.loc[df["outcome"] == "Accepted", "decision_date"].dropna()
    fig, ax = plt.subplots(figsize=(9, 6))
    if len(dates):
        nums = mdates.date2num(dates)
        bins = np.arange(nums.min(), nums.max() + 3, 3)  # 3-day-wide bins
        ax.hist(nums, bins=bins, color="#2b6cb0", edgecolor="white", label="acceptances")
        ax.xaxis_date()
        fig.autofmt_xdate()
    ax.set_title("Acceptances over time (3-day bins)")
    ax.set_xlabel("Decision date")
    ax.set_ylabel("Number of acceptances (count)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def box_gpa_by_outcome(df, path):
    """Boxplot of GPA distribution grouped by outcome."""
    order = ["Accepted", "Rejected", "Waitlisted", "Interviewed"]
    present = [o for o in order if o in df["outcome"].unique()]
    data = [df.loc[(df["outcome"] == o) & (df["GPA"].between(0, 4.0)), "GPA"].dropna()
            for o in present]
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.boxplot(data, labels=present, showfliers=True)
    ax.set_title("GPA distribution by outcome")
    ax.set_xlabel("Outcome")
    ax.set_ylabel("GPA (4.0 scale)")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def correlation_heatmap(df, path, cols=("GPA", "GRE", "GRE V", "GRE AW")):
    """Correlation heatmap for the numeric columns."""
    corr = df[list(cols)].corr()
    fig, ax = plt.subplots(figsize=(7, 6))
    im = ax.imshow(corr.to_numpy(), vmin=-1, vmax=1, cmap="coolwarm")
    ax.set_xticks(range(len(cols)))
    ax.set_yticks(range(len(cols)))
    ax.set_xticklabels(cols, rotation=45, ha="right")
    ax.set_yticklabels(cols)
    for i in range(len(cols)):
        for j in range(len(cols)):
            ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center",
                    color="black")
    ax.set_title("Numeric correlation heatmap")
    fig.colorbar(im, ax=ax, label="Pearson r")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


# --------------------------------------------------------------------------- #
# Analytical summary PDF (assignment section 8)
# --------------------------------------------------------------------------- #
def _pdf_page(pdf, title, body):
    """Render one text page (title + wrapped body) into ``pdf``."""
    fig = plt.figure(figsize=(8.5, 11))
    fig.text(0.08, 0.94, title, fontsize=15, fontweight="bold", va="top")
    wrapped = []
    for para in body.split("\n"):
        wrapped.extend(textwrap.wrap(para, width=95) or [""])
    fig.text(0.08, 0.88, "\n".join(wrapped), fontsize=10.5, va="top", family="monospace")
    plt.axis("off")
    pdf.savefig(fig)
    plt.close(fig)


def build_analytics_pdf(path, stats):
    """Write ``analytics.pdf`` from a dict of code-computed ``stats``.

    Every number in the prose comes from ``stats`` (computed in the notebook),
    so nothing is hard-coded -- the PDF interprets values the cleaning pipeline
    produced.
    """
    with PdfPages(path) as pdf:
        _pdf_page(pdf, "Module 8 -- Grad Cafe: Analytical Summary", (
            "This report summarizes the cleaned Grad Cafe dataset and the SciPy\n"
            "statistical analyses run in module_8.ipynb. All figures are generated\n"
            "by code from the cleaned DataFrame; the text interprets them.\n\n"
            f"Cleaned dataset: {stats['clean_rows']:,} rows x {stats['clean_cols']} columns "
            f"(from {stats['raw_rows']:,} raw rows).\n\n"
            "Q1. Average GRE of accepted PhD applicants\n"
            f"    -> {stats['avg_gre_accepted_phd']} "
            f"(n = {stats['n_gre_accepted_phd']} applicants with a valid GRE).\n\n"
            "Q2. Average GPA of accepted Master's applicants\n"
            f"    -> {stats['avg_gpa_accepted_masters']} "
            f"(n = {stats['n_gpa_accepted_masters']} applicants with a valid GPA).\n"
            "    Both averages use only valid, non-missing scores, so they describe\n"
            "    the reporting subset rather than every accepted applicant."
        ))

        _pdf_page(pdf, "Q3. Shortcomings of inferring decision_date", (
            "decision_date is inferred from a free-text status/notification field plus\n"
            "the term year. Key shortcomings:\n\n"
            "1. Ambiguous / missing year. The notification text carries only a month and\n"
            "   day (e.g. 'Feb 10'); we borrow the year from the term (e.g. Fall 2026).\n"
            "   Decisions that actually land in the calendar year before or after the\n"
            "   term are dated incorrectly, which can even make days_to_decision negative.\n\n"
            "2. Free-text fragility. Users type statuses inconsistently ('Interview' vs\n"
            "   'Interviewed', extra words, typos, blanks). Any format we did not\n"
            "   anticipate is silently dropped to a missing date.\n\n"
            "3. No timezone / self-reported lag. Dates are entered by applicants after\n"
            "   the fact, so they approximate rather than record the true decision date;\n"
            "   day-level precision is optimistic."
        ))

        _pdf_page(pdf, "Q4-Q6. Statistical analyses", (
            "Q4. Correlation between GPA and GRE-related measures.\n"
            f"    Pearson GRE vs GRE V: r = {stats['gre_grev_r']}, "
            f"p = {stats['gre_grev_p']} (n = {stats['gre_grev_n']}).\n"
            f"    GPA vs GRE ({stats['gpa_gre_method']}): r = {stats['gpa_gre_r']}, "
            f"p = {stats['gpa_gre_p']} (n = {stats['gpa_gre_n']}).\n"
            f"    {stats['corr_interpretation']}\n\n"
            "Q5. Group comparison of GPA (Accepted vs Rejected).\n"
            f"    Test: {stats['group_test']}; statistic = {stats['group_stat']}, "
            f"p = {stats['group_p']}.\n"
            f"    Accepted mean GPA = {stats['accepted_gpa_mean']} "
            f"(n = {stats['accepted_gpa_n']}); "
            f"Rejected mean GPA = {stats['rejected_gpa_mean']} "
            f"(n = {stats['rejected_gpa_n']}).\n"
            f"    {stats['group_interpretation']}\n\n"
            "Q6. Chi-square: Degree vs US/International.\n"
            f"    chi2 = {stats['chi2_stat']}, p = {stats['chi2_p']}, "
            f"dof = {stats['chi2_dof']}.\n"
            f"    {stats['chi2_interpretation']}"
        ))

        _pdf_page(pdf, "Q7. Remaining data-quality issues", (
            "Even after cleaning, several issues remain:\n\n"
            "* Sparse GRE reporting. Only a small minority of rows carry any GRE score,\n"
            "  so every GRE statistic describes a self-selected reporting subset.\n\n"
            "* Residual out-of-range values. Some GPAs sit outside 0-4.0 (e.g. 10-point\n"
            "  or percentage scales); has_valid_gpa flags but does not repair them.\n\n"
            "* Self-reported, unverified entries. Programs, universities, and outcomes are\n"
            "  free text; near-duplicate spellings survive standardization.\n\n"
            "* Inferred, sometimes-negative days_to_decision from the date logic in Q3.\n\n"
            "* Class imbalance. Terms and outcomes are dominated by a single value, which\n"
            "  limits how far group comparisons generalize.\n\n"
            "Takeaway: the dataset is now analysis-ready for descriptive EDA, but the\n"
            "numbers should be read as patterns in self-reported data, not ground truth."
        ))
    return path
